<?php

/*
service_worker_page_attachments_alter(&$variables) {
  
}
*/

function service_worker_preprocess_html(&$variables) {
  $variables['#attached']['drupalSettings']['service_worker']['filename']  = \Drupal::config('service_worker.settings')->get('filename');
  $variables['#attached']['library'][] = 'service_worker/register-sw';
  $variables['#attached']['library'][] = 'service_worker/a2hs';  
  
  $push_enabled = \Drupal::config('service_worker.settings')->get('enable_push_notifications');
  if( $push_enabled == true || $push_enabled == 1 ){
    $vid = \Drupal::config('service_worker.settings')->get('vapid_public_key');
    $variables['#attached']['drupalSettings']['service_worker']['vapid_public_key'] = $vid;
    if (!empty($vid)) {
      $variables['#attached']['library'][] = 'service_worker/push-notifications';
    }
  }

  $variables['#attached']['html_head'][] = [
      array(
      '#tag' => 'link',
      '#attributes' => array(
        'rel' => 'manifest',
        'href' => '/'.\Drupal::config('service_worker.settings')->get('manifestfilename').'.webmanifest',
      ),
    ),
  'manifest'];
  $variables['#attached']['html_head'][] = [
      array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'theme-color',
        'content' => \Drupal::config('service_worker.settings')->get('themecolor'),
      ),
    ),
  'theme-color'];
}

function service_worker_theme(){
  return array(
    'a2hs' => array(
      'variables' => array(
        'prefix' => NULL,
        'text' => 'Ajouter au burreau'
      ),
      'template' => 'a2hs',
    ),
  );
}

function template_preprocess_a2hs(&$variables) {
  $variables['attributes']['title'] = 'Installez le site sur votre bureau';
}